In [2]:
import numpy as np
import tensorflow as tf

xy = np.loadtxt("softmax_dataset.csv",delimiter = " ", dtype = np.float32)
x_data = xy[:, 0:4]
y_data = xy[:, 4:]
nb_classes = 3
X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 3])

W = tf.Variable(tf.random_normal([4, nb_classes]), name = "weight")
b = tf.Variable(tf.random_normal([nb_classes]), name = "bias")

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b )

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.03).minimize(cost)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(200+1):
    sess.run(optimizer, feed_dict = {X :x_data, Y : y_data})
    if step % 20 == 0 :
        print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))
        
test = sess.run(hypothesis, feed_dict={X : [[1, 11, 7, 9], 
                                            [1, 3 , 4, 3],
                                            [1, 1, 0 , 1]]})

print(test, sess.run(tf.argmax(test, 1)))

0 1.64785
20 1.06581
40 0.760683
60 0.687888
80 0.672495
100 0.664781
120 0.658643
140 0.653268
160 0.648441
180 0.644043
200 0.639994
[[  2.06870052e-15   8.27471077e-01   1.72528952e-01]
 [  1.73699320e-07   1.38908252e-01   8.61091614e-01]
 [  7.29283690e-03   6.97904527e-01   2.94802576e-01]] [1 2 1]
